import I18nProvider from '@/lib/i18n-provider';
import "./globals.css";

export const metadata = {
  title: "Wathiq",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body>
        <I18nProvider>{children}</I18nProvider>
      </body>
    </html>
  );
}
