import "./globals.css";

export const metadata = {
  title: "Wathiq",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body>
       {children}
      </body>
    </html>
  );
}
